name: zam_core
version: 0.0.2
description: Core library for all zamstation packages which contains the most basic classes like the NamedException to get started.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4
