name: zam_core
version: 0.0.1
description: Core Zamstation Library.
homepage: https://zamstation.com
repository: https://github.com/Zamstation/zam_core
authors:
  - Amsakanna

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4
