name: zam_core
version: 0.4.0
description: Core library for all zamstation packages which contains the most basic classes.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_core

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.3.0
  rxdart: ^0.27.1

dev_dependencies:
  test: ^1.17.4
