name: zam_core
version: 0.6.0
description: Core library for all zamstation packages which contains the most basic classes.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_core

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.8.0
  rxdart: ^0.27.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
