name: zam_core
description: Core Zamstation Library.
version: 0.0.1
publish_to: none
homepage: www.zamstation.com
authors:
  - Amsakanna

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.4
